import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='max-w-7xl mx-auto'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
